### ISSUE TITLE
typing end UI

### ISSUE THREAD

**Issue by Rhodanthe1116** [Rhodanthe1116/lyrics-typing#18]
## Design

https://www.figma.com/file/cWYuj9RSKZHYvsqqjBJald/Kanatype?node-id=128%3A492

## Actual

- 結束後，input還在且可以繼續打
- 顯示WPM

## Expected

- 結束後，input應該要消失。
- 顯示CPM (CPM = WPM * 5，可以直接把現在code裡面的除5拿掉)
- Time四捨五入到整數
- Accuracy到小數點第一位
- 在最後顯示與首頁類似的相關歌曲（目前先做Same Albums / Artists 這個就好了）

## musixmatch api

you may want to use:

- track.search with random page
- album.tracks.get
- artist.albums.get

**Comment by linboj** [comment]
關於Same Albums / Artists部分，因為回傳資料的track裡只有album_name、artist_id、artist_name，沒有album_id。
要Same Albums / Artists變成要先用artist.albums.get抓回特定artist的所有albums，然後用album_name抓出album_id，再用album.tracks.get去抓同album的其他tracks，如果同album沒有其他tracks再track.search抓同artist的其他tracks，這樣至少會需要call兩次API。
還是只要Same Artists就好? 只需要用track.search抓出artist的其他tracks，只會call一次API。

**Comment by Rhodanthe1116** [comment]
@linboj 

musixmatch的track.get回傳的track，應該是有可能有album_id，也可能不會有（他的文件都寫得跟實際上會有落差，要實際去他的swagger打打看）

不過目前graphql track的裡面確實是沒有寫到albumId，不知道你會不會想寫寫

目前應該先用track.search + artistId + albumId 搜搜看效果如何好了，應該比較簡單
如果不行的話（或沒有albumId的時候），只搜same artists也可以～

另外幫我把搜的結果先放10個(各五個)好了，figma上面只有兩個，因為我懶得拉XD
然後希望可以用page來讓他有random的效果，不過不確定實際上執行起來會遇到什麼問題，如果不行也就先至少可以顯示結果就好～

**Comment by Rhodanthe1116** [comment]
musixmatch的track.get回傳的track，應該是有可能有album_id，也可能不會有（他的文件都寫得跟實際上會有落差，要實際去他的swagger打打看）

不過目前graphql track的裡面確實是沒有寫到albumId，不知道你會不會想寫寫

目前應該先用

- track.search + artistId
- album.tracks.get + albumId 

（兩個都會動到graphql）
不過這樣要做兩次query就是了

先搜搜看效果如何好了
如果不行的話（或沒有albumId的時候），只搜same artists也可以～

另外幫我把搜的結果先放10個(各五個)好了，figma上面只有兩個，因為我懶得拉XD
然後search的話希望可以用page來讓他有random的效果，不過不確定實際上執行起來會遇到什麼問題，如果不行也就先至少可以顯示結果就好～

**Comment by linboj** [comment]
musixmatch的track.get回傳的track裡面有album_id，我直接改API跟Interface，Track Type多包含album_id和artist_id?

**Comment by linboj** [comment]
@Rhodanthe1116 

那我直接在MusixmatchAPI增加我需要的function(albumReducer, searchTracksByArtistId, getTracksByAlbumId, getAlbumById)
getAlbumById部分會回傳一個Album裡面會包含coverart，應該可以處理#24

只是完成上面這些一定會動到apollo跟Interfaces部分，有機會把之前的設計搞亂，這部分要先改還是完整規畫完再改?

**Comment by Rhodanthe1116** [comment]
@linboj 

- searchTracks其實可以用原本的那個 加入參數就好？

其他看起來沒問題，麻煩你了！直接改沒關係，有問題之後再處理整合就好，我們快沒時間了哈哈

**Comment by linboj** [comment]
@Rhodanthe1116 

musixmatch把album_coverart資訊都拿掉了

#24
