### ISSUE TITLE
Typing result bug

### ISSUE THREAD

**Issue by Rhodanthe1116** [Rhodanthe1116/lyrics-typing#28]
## Actual

全對但都會說我有地方錯

![Screenshot_20210624-065142.png](https://user-images.githubusercontent.com/16717793/123177912-c048ce80-d4b8-11eb-8555-29435a6f8b09.png)

## Expected

全對

**Comment by linboj** [comment]
可能跟一些標點符號(半形、全形)和空格有關係，空格不會呈現但會算在character裡，目前按空白鍵跟Enter同樣是sumbit的意思

小夜子歌詞總共有13句，有可能每句最後都是空格，所以才會出現有地方錯誤

![image](https://user-images.githubusercontent.com/66619942/123192975-85559380-d4d6-11eb-9753-e22f6515c6d8.png)

**Comment by linboj** [comment]
更新

可能跟'\n'有關係才對，雖然呈現時以br element取代掉了，但傳入useTyping的text好像依然存在'\n'沒處理。

測試過幾首，wrong character都跟呈現出來的行數一樣。
