### ISSUE TITLE
Start game

### ISSUE THREAD

**Issue by Rhodanthe1116** [Rhodanthe1116/lyrics-typing#29]
## Actual

按下START後沒有開始計時打字

![Screenshot_20210624-065439.png](https://user-images.githubusercontent.com/16717793/123178080-1453b300-d4b9-11eb-8dbc-88d1297714ce.png)

## Expected

按下START後開始計時打字，且應該要自動對焦+全螢幕

**Comment by linboj** [comment]
@Rhodanthe1116 

reset後也要馬上開始計時嗎?

**Comment by Rhodanthe1116** [comment]
Reset 先不要管他好了

@linboj
